services:
  api:
    container_name: codecompile_api
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
      
    ports:
      - 4000:4000
    
    depends_on:
      - postgres
      - redis
        
    links:
      - postgres
      - redis
      
    environment:
      HASH_SECRET_KEY: SJidsjsiDJ920jSD74hbf3

      JWT_SECRET_KEY: SdunsbDOIJIUOJinm8398198NJ
      JWT_ISSUER: compile.dsvinka.ru
      JWT_AUDIENCE: compile.dsvinka.ru
      JWT_ACCESS_TOKEN_LIFE_MINUTES: 2880
      JWT_REFRESH_TOKEN_LIFE_MINUTES: 10080

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: codecompile_api
      POSTGRES_USERNAME: NotUser879
      POSTGRES_PASSWORD: ChangeMeNotUser879

      REDIS_HOST: redis:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      
    networks:
      - codecompile
        
    restart: unless-stopped


  services_docker:
    container_name: codecompile_services_docker
    image: services-docker
    build:
      context: .
      dockerfile: Services.Docker/Dockerfile
      
    depends_on:
      - postgres
      - redis

    links:
      - postgres
      - redis
      
    privileged: true;
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: codecompile_services_docker
      POSTGRES_USERNAME: NotUser879
      POSTGRES_PASSWORD: ChangeMeNotUser879

      REDIS_HOST: redis:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      
      DOCKER_HOST: "unix:///var/run/docker.sock",
        
    networks:
      - codecompile
        
    restart: unless-stopped
  
  
  postgres:
    container_name: codecompile_postgres
    image: postgres
    environment:
      POSTGRES_USER: NotUser879
      POSTGRES_PASSWORD: ChangeMeNotUser879
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - codecompile
      
    restart: unless-stopped
    
    
  pgadmin:
    container_name: codecompile_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: ChangeMeAdmin879
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    
    ports:
      - "5050:80"
    networks:
      - codecompile
      
    restart: unless-stopped


  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - codecompile
    volumes:
      - cache:/data


networks:
  codecompile:
    driver: bridge

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
  cache:
    driver: local